### ISSUE TITLE
Camera Modifications, facing direction fixes.

### ISSUE THREAD

**Issue by yaahc** [yaahc/gameoff#15]
I was working on hitboxes and thought I could arbitrarily change the rotation of a component to change its facing direction which I could use the vector from to figure out the angle between the facing vector and the vector from the player to any given entity when determining if they're inside the cone of a hitbox.

It turns out this was a bad idea. The rotation is tied to the orientation of the sprite. Which is fine. But our camera is a child entity of the player entity. Which in amethyst speak means that its coordinate space is relative to the player, so wherever the player is x:0, y:0 for the camera, which is how we keep the camera centered. Messing with the player entities rotation did, shall we say, weird things to the camera. Part of this was because I misinterpreted how the quaternion for rotation works, I thought it was a vector indicating the direction it's facing. It's not; it's a vector of angles around the three axes. I don't think we're ever going to want to rotate the player entity relative to the camera, but we may or may not want facing direction support. And we would like to have the camera follow the player but not be tied firmly to the player.

Tasks are as follows
- [ ] initialize the camera without the player as its parent entity.
- [ ] Add a camera movement system that reads the player and camera positions and moves the camera nearer the player if the player starts to move far away. The primary goal here is to minimize how often we redraw the background, which can cause some gross looking effects on LCD screens. 
- [ ] Add a new component that has a Vector3 that indicates what direction the entity is currently facing. This component will probably apply to the player and all enemies/allies, so use a DenseVecStorage.

**Comment by yaahallo** [comment]
I think @TheBlueSmoke is going to work on this one

**Comment by yaahallo** [comment]
I'm going to be adding a new entity called "Group" that is the parent entity of the player. I think this is necessary for the group rotation feature in the Allies issue. I think that for any rotation I apply to the group I'll have to apply its inverse to all of the entities in the group in order to prevent them from turning, but if this is happening then you can probably leave the camera as the child of the player entity itself.

I don't really think this matters though because we still want less aggressive background redrawing.
